### ISSUE TITLE
Meta Issue: framegear

### ISSUE THREAD

**Issue by cnasc** [coinbase/onchainkit#146]
### Describe the solution you'd like

At some point it would be nice to group these into a project, but for the time being listing some outstanding ideas:

- [ ] show frame payload HTML tags (and copy button)
- [ ] show frame payload as an `onchainkit` metadata object (and copy button)
- [ ] verification
  - [x] show required tags even when not present in payload (#176)
  - [ ] show all possible tags (possibly collapsed) even if not present in payload
- [x] distinct button icons for distinct button actions (e.g., `post_redirect`, `mint`, and `link` buttons) (#203)
- [ ] rendered frame should support all button actions
  - [x] `post`
  - [x] `post_redirect`
  - [x] `link`
  - [ ] `mint`
- [x] rendered frame should include text input in mock request (https://github.com/coinbase/onchainkit/pull/201)
- [ ] allow user to select certain simulated conditions (e.g., liked/recasted, followed, etc.)
- [x] favicon (awaiting design) (https://github.com/coinbase/onchainkit/pull/204)
- [ ] Identify when a frame can accept debug actions, inform user what is possible
- [ ] more comprehensive light/dark mode styling (see #190)
- [x] support `fc:frame:state` tag (see https://github.com/coinbase/onchainkit/pull/193#issuecomment-1963041332) (#232)
- [ ] frame input bug (state seems to persist after next frame renders)
- [ ] more sophisticated state handling (page through previous, time travel debugger)

**Comment by taycaldwell** [comment]
PR: https://github.com/coinbase/onchainkit/pull/200

Rendered frame should support all button actions
Distinct button icons for distinct button actions
  -  `post_redirect`
  - `link`

**Comment by cnasc** [comment]
@huntertdiamond I see you added a commit to add simulated conditions to the frame. Do you want to drive on that one? And/or cool if I build on it sometime in the next few days?

**Comment by anader123** [comment]
gm there appears to be a bug with framegear where post action buttons don't hit the target endpoint and posts default go to the posturl

**Comment by cpcramer** [comment]
Frames has been deprecated.
